# Configure here general information about the environment, such as the server connection details for example
# No information about specific project should appear here

#----- SonarQube server URL (default to SonarCloud)
sonar.projectKey=SensetheScene
sonar.projectName=SensetheScene
sonar.host.url=http://localhost:9000
sonar.token=sqp_7f42ac17d8887baf5240170ebd80a49ff3bf17e5
sonar.sources=. 
sonar.exclusions=**/*.ipynb, **/*.ipynb/**, Main.ipynb
sonar.python.version=3.12.7 # Or your Python version
