# General SonarQube configuration
sonar.projectKey=SensetheScene
sonar.projectName=SensetheScene
sonar.host.url=http://localhost:9000
sonar.token=sqp_7f42ac17d8887baf5240170ebd80a49ff3bf17e5

# Source files and exclusions
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/test_*.py, tests/Standardization_Test.py, tests/Mapping_Test.py
sonar.exclusions=**/*.ipynb, **/*.ipynb/**, Main.ipynb

# Python version
sonar.python.version=3.12.7
